services:
  _defaults:
    autowire:      true
    autoconfigure: true
    public:        true
    bind:
      $scrollListByTag: '%scroll_list_bytag%'
      $columnsObjsByTag: '%columns_objs_bytag%'
      $locales: "%pumukit.locales%"

  Pumukit\TimedPubDecisionsBundle\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']


  Pumukit\TimedPubDecisionsBundle\Command\:
    resource: '../../Command/'
    tags: ['console.command']

  Pumukit\TimedPubDecisionsBundle\EventListener\BackofficeListener:
    class: Pumukit\TimedPubDecisionsBundle\EventListener\BackofficeListener
    tags:
      - { name: "kernel.event_listener", event: "publication.submit", method: "onPublicationSubmit" }

  Pumukit\TimedPubDecisionsBundle\Services\MenuService:
    class: Pumukit\TimedPubDecisionsBundle\Services\MenuService
    tags:
      - { name: "pumukitnewadmin.menuitem" }
